image: growerp/flutter-sdk-image:3.16.0


# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .pub-cache/global_packages

stages:
  - analyze_and_test
  - build_release

before_script:
  - export PATH="$PATH":"$HOME/.flutter-sdk/.pub-cache/bin"
  - flutter --version
  - flutter pub get
  - dart run build_runner build --delete-conflicting-outputs

analyze_and_test:
  stage: analyze_and_test
  script:
    - flutter analyze
    - flutter test --coverage
  tags:
    - docker

build_release:
  stage: build_release
  script:
    - flutter build apk --split-per-abi --build-number=$CI_PIPELINE_ID
  tags:
    - docker
  only:
    - main
    - release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk