image: fischerscode/flutter:stable


# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .pub-cache/global_packages

stages:
  - analyze_and_test

before_script:
  - export PATH="$PATH":"$HOME/.flutter-sdk/.pub-cache/bin"
  - flutter --version
  - flutter pub get

analyze_and_test:
  stage: analyze_and_test
  script:
    - flutter analyze
    - flutter test --coverage
  tags:
    - docker